<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION ARTIFICIAL   (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="LAB.EXE" EXE_PATH="/home/micah/tmp/roboody/LAB.EXE" EXE_FORMAT="Old-style DOS Executable (MZ)" IMAGE_BASE="0000:0000">
    <INFO_SOURCE USER="micah" TOOL="Ghidra 11.4.2" TIMESTAMP="Sat Oct 04 21:38:05 PDT 2025" />
    <PROCESSOR NAME="x86" LANGUAGE_PROVIDER="x86:LE:16:Real Mode:default" ENDIAN="little" />
    <DATATYPES>
        <STRUCTURE NAME="OLD_IMAGE_DOS_HEADER" NAMESPACE="/DOS" SIZE="0x1c">
            <MEMBER OFFSET="0x0" DATATYPE="char[2]" DATATYPE_NAMESPACE="/" NAME="e_magic" SIZE="0x2">
                <REGULAR_CMT>Magic number</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cblp" SIZE="0x2">
                <REGULAR_CMT>Bytes of last page</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cp" SIZE="0x2">
                <REGULAR_CMT>Pages in file</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x6" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_crlc" SIZE="0x2">
                <REGULAR_CMT>Relocations</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cparhdr" SIZE="0x2">
                <REGULAR_CMT>Size of header in paragraphs</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xa" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_minalloc" SIZE="0x2">
                <REGULAR_CMT>Minimum extra paragraphs needed</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_maxalloc" SIZE="0x2">
                <REGULAR_CMT>Maximum extra paragraphs needed</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xe" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ss" SIZE="0x2">
                <REGULAR_CMT>Initial (relative) SS value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_sp" SIZE="0x2">
                <REGULAR_CMT>Initial SP value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x12" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_csum" SIZE="0x2">
                <REGULAR_CMT>Checksum</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ip" SIZE="0x2">
                <REGULAR_CMT>Initial IP value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x16" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cs" SIZE="0x2">
                <REGULAR_CMT>Initial (relative) CS value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_lfarlc" SIZE="0x2">
                <REGULAR_CMT>File address of relocation table</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1a" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ovno" SIZE="0x2">
                <REGULAR_CMT>Overlay number</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="OLD_IMAGE_DOS_RELOC" NAMESPACE="/DOS" SIZE="0x4">
            <MEMBER OFFSET="0x0" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="offset" SIZE="0x2" />
            <MEMBER OFFSET="0x2" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="segment" SIZE="0x2" />
        </STRUCTURE>
    </DATATYPES>
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="BDA" START_ADDR="0040:0000" LENGTH="0x100" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="DATA" START_ADDR="0100:0000" LENGTH="0xc630" PERMISSIONS="rwx" COMMENT="" />
        <MEMORY_SECTION NAME="CODE" START_ADDR="0d63:0000" LENGTH="0x8e60" PERMISSIONS="rwx" COMMENT="" />
        <MEMORY_SECTION NAME="COPYPROT" START_ADDR="2549:0000" LENGTH="0x5df" PERMISSIONS="rwx" COMMENT="" />
        <MEMORY_SECTION NAME="HEADER" START_ADDR="HEADER::OTHER:00000000" LENGTH="0x200" PERMISSIONS="r" COMMENT="" />
    </MEMORY_MAP>
    <REGISTER_VALUES>
        <REGISTER_VALUE_RANGE REGISTER="SP" VALUE="0x400" START_ADDRESS="0d63:0000" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="CS" VALUE="0xd63" START_ADDRESS="0d63:0000" LENGTH="0x8e60" />
        <REGISTER_VALUE_RANGE REGISTER="SS" VALUE="0x2509" START_ADDRESS="0d63:0000" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="DS" VALUE="0x100" START_ADDRESS="0d63:0000" LENGTH="0x8e60" />
        <REGISTER_VALUE_RANGE REGISTER="CS" VALUE="0x2549" START_ADDRESS="2549:0000" LENGTH="0x5df" />
    </REGISTER_VALUES>
    <CODE>
        <CODE_BLOCK START="0d63:0000" END="0d63:00d4" />
        <CODE_BLOCK START="0d63:00d6" END="0d63:00e4" />
        <CODE_BLOCK START="0d63:00e6" END="0d63:00f4" />
        <CODE_BLOCK START="0d63:00f6" END="0d63:0104" />
        <CODE_BLOCK START="0d63:0106" END="0d63:0114" />
        <CODE_BLOCK START="0d63:0116" END="0d63:0124" />
        <CODE_BLOCK START="0d63:0126" END="0d63:0134" />
        <CODE_BLOCK START="0d63:0136" END="0d63:0144" />
        <CODE_BLOCK START="0d63:0146" END="0d63:0192" />
        <CODE_BLOCK START="0d63:01a0" END="0d63:0266" />
        <CODE_BLOCK START="0d63:0268" END="0d63:032d" />
        <CODE_BLOCK START="0d63:032f" END="0d63:0337" />
        <CODE_BLOCK START="0d63:0339" END="0d63:033d" />
        <CODE_BLOCK START="0d63:033f" END="0d63:0347" />
        <CODE_BLOCK START="0d63:0349" END="0d63:034d" />
        <CODE_BLOCK START="0d63:034f" END="0d63:0357" />
        <CODE_BLOCK START="0d63:0359" END="0d63:035d" />
        <CODE_BLOCK START="0d63:035f" END="0d63:0367" />
        <CODE_BLOCK START="0d63:0369" END="0d63:036d" />
        <CODE_BLOCK START="0d63:036f" END="0d63:0373" />
        <CODE_BLOCK START="0d63:0375" END="0d63:0379" />
        <CODE_BLOCK START="0d63:037b" END="0d63:041f" />
        <CODE_BLOCK START="0d63:0422" END="0d63:046f" />
        <CODE_BLOCK START="0d63:0471" END="0d63:04b3" />
        <CODE_BLOCK START="0d63:04b5" END="0d63:04df" />
        <CODE_BLOCK START="0d63:04e1" END="0d63:04f3" />
        <CODE_BLOCK START="0d63:04f5" END="0d63:0520" />
        <CODE_BLOCK START="0d63:0530" END="0d63:0795" />
        <CODE_BLOCK START="0d63:0797" END="0d63:07d8" />
        <CODE_BLOCK START="0d63:07da" END="0d63:09b2" />
        <CODE_BLOCK START="0d63:09b4" END="0d63:09cb" />
        <CODE_BLOCK START="0d63:09cd" END="0d63:09e7" />
        <CODE_BLOCK START="0d63:09f0" END="0d63:0af5" />
        <CODE_BLOCK START="0d63:0b00" END="0d63:0b8e" />
        <CODE_BLOCK START="0d63:0b90" END="0d63:0e33" />
        <CODE_BLOCK START="0d63:0e35" END="0d63:0e3d" />
        <CODE_BLOCK START="0d63:0e3f" END="0d63:0eab" />
        <CODE_BLOCK START="0d63:0eb0" END="0d63:0ec8" />
        <CODE_BLOCK START="0d63:0eca" END="0d63:0ff8" />
        <CODE_BLOCK START="0d63:0ffa" END="0d63:1130" />
        <CODE_BLOCK START="0d63:1133" END="0d63:1215" />
        <CODE_BLOCK START="0d63:1217" END="0d63:12cd" />
        <CODE_BLOCK START="0d63:12d0" END="0d63:13bb" />
        <CODE_BLOCK START="0d63:13bd" END="0d63:13c3" />
        <CODE_BLOCK START="0d63:13c5" END="0d63:13cb" />
        <CODE_BLOCK START="0d63:13cd" END="0d63:13d3" />
        <CODE_BLOCK START="0d63:13d5" END="0d63:13db" />
        <CODE_BLOCK START="0d63:13dd" END="0d63:13e3" />
        <CODE_BLOCK START="0d63:13e5" END="0d63:13eb" />
        <CODE_BLOCK START="0d63:13ed" END="0d63:13f3" />
        <CODE_BLOCK START="0d63:13f5" END="0d63:13fb" />
        <CODE_BLOCK START="0d63:13fd" END="0d63:1403" />
        <CODE_BLOCK START="0d63:1405" END="0d63:1410" />
        <CODE_BLOCK START="0d63:1412" END="0d63:1499" />
        <CODE_BLOCK START="0d63:149b" END="0d63:14aa" />
        <CODE_BLOCK START="0d63:14ac" END="0d63:154e" />
        <CODE_BLOCK START="0d63:1550" END="0d63:16d1" />
        <CODE_BLOCK START="0d63:16d3" END="0d63:16dc" />
        <CODE_BLOCK START="0d63:16de" END="0d63:16e7" />
        <CODE_BLOCK START="0d63:16e9" END="0d63:1ca1" />
        <CODE_BLOCK START="0d63:1ca3" END="0d63:2080" />
        <CODE_BLOCK START="0d63:2090" END="0d63:23cc" />
        <CODE_BLOCK START="0d63:2401" END="0d63:2632" />
        <CODE_BLOCK START="0d63:2634" END="0d63:266c" />
        <CODE_BLOCK START="0d63:266e" END="0d63:266f" />
        <CODE_BLOCK START="0d63:2671" END="0d63:278e" />
        <CODE_BLOCK START="0d63:2790" END="0d63:27a7" />
        <CODE_BLOCK START="0d63:27a9" END="0d63:2918" />
        <CODE_BLOCK START="0d63:291a" END="0d63:2922" />
        <CODE_BLOCK START="0d63:2924" END="0d63:29a5" />
        <CODE_BLOCK START="0d63:29a7" END="0d63:29cd" />
        <CODE_BLOCK START="0d63:2aae" END="0d63:2d87" />
        <CODE_BLOCK START="0d63:2dad" END="0d63:2de3" />
        <CODE_BLOCK START="0d63:2de5" END="0d63:2e83" />
        <CODE_BLOCK START="0d63:2e85" END="0d63:2f97" />
        <CODE_BLOCK START="0d63:2f99" END="0d63:2fae" />
        <CODE_BLOCK START="0d63:2fb0" END="0d63:30fa" />
        <CODE_BLOCK START="0d63:30fc" END="0d63:310d" />
        <CODE_BLOCK START="0d63:310f" END="0d63:3123" />
        <CODE_BLOCK START="0d63:3125" END="0d63:313c" />
        <CODE_BLOCK START="0d63:313e" END="0d63:322f" />
        <CODE_BLOCK START="0d63:3231" END="0d63:323b" />
        <CODE_BLOCK START="0d63:323d" END="0d63:3245" />
        <CODE_BLOCK START="0d63:3247" END="0d63:324f" />
        <CODE_BLOCK START="0d63:3251" END="0d63:327c" />
        <CODE_BLOCK START="0d63:327e" END="0d63:3293" />
        <CODE_BLOCK START="0d63:3295" END="0d63:32ab" />
        <CODE_BLOCK START="0d63:32ad" END="0d63:32b7" />
        <CODE_BLOCK START="0d63:32b9" END="0d63:32c1" />
        <CODE_BLOCK START="0d63:32c3" END="0d63:32cb" />
        <CODE_BLOCK START="0d63:32cd" END="0d63:32e8" />
        <CODE_BLOCK START="0d63:32ea" END="0d63:334e" />
        <CODE_BLOCK START="0d63:3350" END="0d63:3377" />
        <CODE_BLOCK START="0d63:3379" END="0d63:3409" />
        <CODE_BLOCK START="0d63:340b" END="0d63:3460" />
        <CODE_BLOCK START="0d63:3462" END="0d63:34c2" />
        <CODE_BLOCK START="0d63:34c4" END="0d63:350a" />
        <CODE_BLOCK START="0d63:3510" END="0d63:35aa" />
        <CODE_BLOCK START="0d63:35ff" END="0d63:3613" />
        <CODE_BLOCK START="0d63:3615" END="0d63:3635" />
        <CODE_BLOCK START="0d63:3637" END="0d63:3642" />
        <CODE_BLOCK START="0d63:3644" END="0d63:367e" />
        <CODE_BLOCK START="0d63:3680" END="0d63:36df" />
        <CODE_BLOCK START="0d63:36e1" END="0d63:36f7" />
        <CODE_BLOCK START="0d63:36f9" END="0d63:370e" />
        <CODE_BLOCK START="0d63:3710" END="0d63:371b" />
        <CODE_BLOCK START="0d63:371d" END="0d63:374e" />
        <CODE_BLOCK START="0d63:3750" END="0d63:37a9" />
        <CODE_BLOCK START="0d63:37ab" END="0d63:37c0" />
        <CODE_BLOCK START="0d63:37c2" END="0d63:37cd" />
        <CODE_BLOCK START="0d63:37cf" END="0d63:37f1" />
        <CODE_BLOCK START="0d63:37f3" END="0d63:384d" />
        <CODE_BLOCK START="0d63:384f" END="0d63:38b6" />
        <CODE_BLOCK START="0d63:38b8" END="0d63:3aed" />
        <CODE_BLOCK START="0d63:3aef" END="0d63:3b56" />
        <CODE_BLOCK START="0d63:3b58" END="0d63:3c5d" />
        <CODE_BLOCK START="0d63:3c5f" END="0d63:3c67" />
        <CODE_BLOCK START="0d63:3c69" END="0d63:3c71" />
        <CODE_BLOCK START="0d63:3c73" END="0d63:3df0" />
        <CODE_BLOCK START="0d63:3df2" END="0d63:3f3c" />
        <CODE_BLOCK START="0d63:3f64" END="0d63:4028" />
        <CODE_BLOCK START="0d63:402a" END="0d63:406d" />
        <CODE_BLOCK START="0d63:406f" END="0d63:4079" />
        <CODE_BLOCK START="0d63:407b" END="0d63:4085" />
        <CODE_BLOCK START="0d63:4087" END="0d63:4208" />
        <CODE_BLOCK START="0d63:420a" END="0d63:4241" />
        <CODE_BLOCK START="0d63:4243" END="0d63:4262" />
        <CODE_BLOCK START="0d63:4284" END="0d63:429c" />
        <CODE_BLOCK START="0d63:42ae" END="0d63:4442" />
        <CODE_BLOCK START="0d63:4444" END="0d63:444c" />
        <CODE_BLOCK START="0d63:444e" END="0d63:4465" />
        <CODE_BLOCK START="0d63:4467" END="0d63:450c" />
        <CODE_BLOCK START="0d63:450e" END="0d63:45d8" />
        <CODE_BLOCK START="0d63:45da" END="0d63:479f" />
        <CODE_BLOCK START="0d63:47a1" END="0d63:47bb" />
        <CODE_BLOCK START="0d63:47bd" END="0d63:4812" />
        <CODE_BLOCK START="0d63:4814" END="0d63:4840" />
        <CODE_BLOCK START="0d63:4842" END="0d63:4894" />
        <CODE_BLOCK START="0d63:4896" END="0d63:4b75" />
        <CODE_BLOCK START="0d63:4b77" END="0d63:4b84" />
        <CODE_BLOCK START="0d63:4b86" END="0d63:4b92" />
        <CODE_BLOCK START="0d63:4b94" END="0d63:4b97" />
        <CODE_BLOCK START="0d63:4b99" END="0d63:4ba8" />
        <CODE_BLOCK START="0d63:4baa" END="0d63:4bb6" />
        <CODE_BLOCK START="0d63:4bb8" END="0d63:4bc4" />
        <CODE_BLOCK START="0d63:4bc6" END="0d63:4bc9" />
        <CODE_BLOCK START="0d63:4bcb" END="0d63:4d05" />
        <CODE_BLOCK START="0d63:4d07" END="0d63:4d19" />
        <CODE_BLOCK START="0d63:4d1b" END="0d63:4d42" />
        <CODE_BLOCK START="0d63:4d44" END="0d63:4d50" />
        <CODE_BLOCK START="0d63:4d52" END="0d63:4e41" />
        <CODE_BLOCK START="0d63:4e43" END="0d63:4e58" />
        <CODE_BLOCK START="0d63:4e5a" END="0d63:4e72" />
        <CODE_BLOCK START="0d63:4e74" END="0d63:5062" />
        <CODE_BLOCK START="0d63:5064" END="0d63:506f" />
        <CODE_BLOCK START="0d63:5071" END="0d63:507c" />
        <CODE_BLOCK START="0d63:507e" END="0d63:5089" />
        <CODE_BLOCK START="0d63:508b" END="0d63:53b6" />
        <CODE_BLOCK START="0d63:53b8" END="0d63:540a" />
        <CODE_BLOCK START="0d63:540c" END="0d63:564f" />
        <CODE_BLOCK START="0d63:5651" END="0d63:5869" />
        <CODE_BLOCK START="0d63:586b" END="0d63:5878" />
        <CODE_BLOCK START="0d63:587a" END="0d63:58de" />
        <CODE_BLOCK START="0d63:58e0" END="0d63:58e6" />
        <CODE_BLOCK START="0d63:58e8" END="0d63:58ee" />
        <CODE_BLOCK START="0d63:58f0" END="0d63:58f6" />
        <CODE_BLOCK START="0d63:58f8" END="0d63:5a26" />
        <CODE_BLOCK START="0d63:5a28" END="0d63:5a3b" />
        <CODE_BLOCK START="0d63:5a3d" END="0d63:5af7" />
        <CODE_BLOCK START="0d63:5af9" END="0d63:5c30" />
        <CODE_BLOCK START="0d63:5c32" END="0d63:5c49" />
        <CODE_BLOCK START="0d63:5c4b" END="0d63:5c62" />
        <CODE_BLOCK START="0d63:5c64" END="0d63:5ca2" />
        <CODE_BLOCK START="0d63:5d17" END="0d63:5d90" />
        <CODE_BLOCK START="0d63:5d92" END="0d63:5da5" />
        <CODE_BLOCK START="0d63:5da7" END="0d63:5e57" />
        <CODE_BLOCK START="0d63:6016" END="0d63:61d0" />
        <CODE_BLOCK START="0d63:6230" END="0d63:64a2" />
        <CODE_BLOCK START="0d63:64ae" END="0d63:6520" />
        <CODE_BLOCK START="0d63:6545" END="0d63:6be1" />
        <CODE_BLOCK START="0d63:6be3" END="0d63:6c1b" />
        <CODE_BLOCK START="0d63:6c1d" END="0d63:6c25" />
        <CODE_BLOCK START="0d63:6c27" END="0d63:6c37" />
        <CODE_BLOCK START="0d63:6c39" END="0d63:6e12" />
        <CODE_BLOCK START="0d63:6e14" END="0d63:6e1c" />
        <CODE_BLOCK START="0d63:6e1e" END="0d63:6e2e" />
        <CODE_BLOCK START="0d63:6e30" END="0d63:7038" />
        <CODE_BLOCK START="0d63:703a" END="0d63:70c8" />
        <CODE_BLOCK START="0d63:70ca" END="0d63:70d2" />
        <CODE_BLOCK START="0d63:70d4" END="0d63:70e4" />
        <CODE_BLOCK START="0d63:70e6" END="0d63:70fb" />
        <CODE_BLOCK START="0d63:70fd" END="0d63:71a9" />
        <CODE_BLOCK START="0d63:71ab" END="0d63:7281" />
        <CODE_BLOCK START="0d63:7283" END="0d63:729b" />
        <CODE_BLOCK START="0d63:729d" END="0d63:72b8" />
        <CODE_BLOCK START="0d63:72ba" END="0d63:7380" />
        <CODE_BLOCK START="0d63:7382" END="0d63:7476" />
        <CODE_BLOCK START="0d63:7478" END="0d63:754a" />